[package]
name = "day-1-calorie-counting"
version.workspace = true
description.workspace = true
authors.workspace = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
